 version: 2

 build:
   os: ubuntu-24.04
   tools:
     python: latest
   jobs:
     install:
       - pip install zensical
     build:
       html:
         - zensical build -f zensical.en.toml
     post_build:
       - mkdir -p $READTHEDOCS_OUTPUT/html/
       - cp --recursive site/en/* $READTHEDOCS_OUTPUT/html/
